/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package Admin;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

/** 
 * MyEclipse Struts
 * Creation date: 09-23-2013
 * 
 * XDoclet definition:
 * @struts.action path="/adminLogin" name="adminLoginForm" input="Admin/adminLogin.jsp" scope="request" validate="true"
 */
public class AdminLoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AdminLoginForm adminLoginForm = (AdminLoginForm) form;// TODO Auto-generated method stub
		
		String _id = adminLoginForm.getId();
		String _pass = adminLoginForm.getPass();
		
		if(_id.equals("admin") && _pass.equals("admin"))
		{
			HttpSession admin = request.getSession();
			admin.setAttribute("admin", _id);
			return mapping.findForward("success");
		}
		
		return mapping.findForward("failure");
	}
}