/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package Admin;

import java.util.Iterator;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import POJO.Booking;


import Hibernate.HibernateUtil;

/** 
 * MyEclipse Struts
 * Creation date: 09-15-2013
 * 
 * XDoclet definition:
 * @struts.action path="/bookingRequests" name="bookingRequestsForm" input="Admin/bookingRequests.jsp" scope="request" validate="true"
 */
public class BookingRequestsAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		BookingRequestsForm bookingRequestsForm = (BookingRequestsForm) form;// TODO Auto-generated method stub
		org.hibernate.Session sess = HibernateUtil.getSessionFactory().openSession();
		org.hibernate.Transaction tr = sess.beginTransaction();

		

		//String SQL_STRING = "FROM DoctorPOJO";
		//Query query = sess.createQuery(SQL_STRING);
		//ArrayList list = (ArrayList) query.list();
		List list = sess.createQuery("FROM Booking").list();
		request.getSession().setAttribute("data", list);
		Iterator itr = list.iterator();
	      while(itr.hasNext()){
	        Booking doc = (Booking) itr.next();
	        System.out.print("--------------------");
	        System.out.print("id: "+ doc.getId());
	        System.out.print(" Name: "+ doc.getName());
	        System.out.print(" surname: "+ doc.getSurname());
	       System.out.print(" email: "+ doc.getEmail());
	       System.out.print(" lengthofstay: "+ doc.getLengthofstay());
	       System.out.print(" persons: "+ doc.getPersons());
	       System.out.print(" Phoneno: "+ doc.getPhoneno());
	       System.out.print(" ArrivalDate: "+ doc.getBookingdate());
	       System.out.print(" UUID: "+ doc.getUUID());
	       System.out.print("--------------------");
	        System.out.println();
	      }
	      tr.commit();
		
		
		
		//request.getSession().setAttribute("data", list);
		
		//sess.getTransaction().commit();
		//HttpSession session=request.getSession(true);
		/*String ss=(String) session.getAttribute("name");
		System.out.println(ss);
		
		if(ss == null)
		{
			System.out.println("going towards failure");
			return mapping.findForward("failure");
			
		}
		
		
		System.out.println("towards success");
		return mapping.findForward("success");
		*/
		
		return mapping.findForward("success");
	}
}