/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package Admin;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;
import org.hibernate.Transaction;
import POJO.*;
import Hibernate.HibernateUtil;

/** 
 * MyEclipse Struts
 * Creation date: 09-23-2013
 * 
 * XDoclet definition:
 * @struts.action path="/search_Booking" name="search_BookingForm" input="Admin/search_Booking.jsp" scope="request" validate="true"
 */
public class Search_BookingAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		Search_BookingForm search_BookingForm = (Search_BookingForm) form;// TODO Auto-generated method stub
		
		String _search = search_BookingForm.getSearch();
		String _value = search_BookingForm.getValue();
		
		Session sess = HibernateUtil.getSessionFactory().openSession();
		Transaction t = sess.beginTransaction();
		
		if(_search.equals("Name"))
		{
			Query q = sess.createQuery("From Booking where name = :n");
			q.setString("n", _value);
			
			List<Booking> check = (List<Booking>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
		
		}
		else if(_search.equals("Email"))
		{
			Query q = sess.createQuery("From Booking where email = :n");
			q.setString("n", _value);
			
			List<Booking> check = (List<Booking>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
		}
		else if(_search.equals("BookingDate"))
		{
			Query q = sess.createQuery("From Booking where bookingdate = :n");
			q.setString("n", _value);
			
			List<Booking> check = (List<Booking>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
		}
		else if(_search.equals("Persons"))
		{
			Query q = sess.createQuery("From Booking where persons = :n");
			q.setString("n", _value);
			
			List<Booking> check = (List<Booking>)q.list();
			request.getSession().setAttribute("data", check);
			
			System.out.println("search complete...");
			
			
			return mapping.findForward("success");
		}
		Query q = sess.createQuery("From Booking where lengthofstay = :n");
		q.setString("n", _value);
		
		List<Booking> check = (List<Booking>)q.list();
		request.getSession().setAttribute("data", check);
		
		System.out.println("search complete...");
		
		
		return mapping.findForward("success");
		
	}
}